config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  namespace :admin do
    get 'homes/top'
  end

  #ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  #ユーザー新規登録、ログイン用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #管理者ログイン用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  scope module: :public do
    resources :users, only: [:show, :edit, :update, :destroy] do
      member do
        get :bookmarks
        get :visited_marks
        get :reviews
      end
    end
    resources :hot_springs, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
      resource :visited_marks, only: [:create, :destroy]
      resources :reviews, only: [:index, :show, :create, :edit, :update, :destroy] do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
        patch 'reports' => 'reviews#report', as: 'report'
      end
    end
    resources :contacts, only: [:new, :create]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :reviews
        get :comments
      end
    end
    resources :reviews, only:[:show, :destroy] do
      resources :comments, only: [:destroy]
      patch 'reports' => 'reviews#report', as: 'report'
    end
    resources :comments, only: [:index]
    resources :hot_springs, only: [:index, :show, :new, :create, :edit, :update]
    resources :contacts, only: [:index, :update]
  end

  # 画像が表示されなくなるため、削除
  # get '*path', controller: 'application', action: 'render_404'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController

  def show
    @review = Review.find(params[:id])
  end
  
  def report
    @review = Review.find(params[:review_id])
    @review.update(report: false)
  end
  
  def destroy
    @review = Review.find(params[:id])
    if @review.destroy
      redirect_to admin_root_path, notice: "クチコミを削除しました"
    else  
      render 'show'
    end
  end
  
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/_report-btn.html.erb
<% if review.report == true %>
  <%= link_to "通報を解除", admin_review_report_path(review), method: :patch, remote: true, class: "btn btn-sm btn-danger" %>
<% else %>
  <%= link_to "通報を解除", admin_review_report_path(review), method: :patch, remote: true, class: "btn btn-sm disabled btn-danger" %>
<% end %>

app/views/admin/reviews/report.js.erb
$("#review_<%= @review.id %> .report-btn").html("<%= j(render 'admin/reviews/report-btn', review: @review) %>");

app/views/admin/reviews/show.html.erb
<div id="review_<%= @review.id %>">
  <div class="container mx-auto mt-3">
    <div class="row mx-auto">
      <div class="col-lg-2 col-md-3 col-sm-4 col-xs-5">
        <%= image_tag @review.user.get_profile_image, size: '50x50', class: "img-responsive rounded-circle" %><br>
        <%= @review.user.username %><br>
        <% if @review.user.username != "ゲスト" %>
          (<%= @review.user.age %>)
        <% end %>
      </div>
      <div class="col-lg-10 col-md-9 col-sm-8 col-xs-7">
        <div class="row">
          <% if @review.images.attached? %>
            <% @review.images.each do |image| %>
              <div class="col-lg-4 col-md-6 mb-3">
                <%= image_tag image, size: '320x200', class: "w-100" %>
              </div>
            <% end %>
          <% end %>
        </div>
  
        <div class="row">
          <div class="col-lg-8">
            <!--レビュータイトル-->
            <h4 class="title mt-3"><%= @review.title %></h4>
            <!--星5段階評価表示-->
            <div id="star-rate<%= @review.id %>"></div>
              <script>
                raty(document.querySelector('#star-rate<%= @review.id %>'),{
                  //星画像の指定などのオプションをここに
                  size      : 36,
                  starOff   : '<%= asset_path('star-off.png') %>',
                  starOn    : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  readOnly: true,
                  score: <%= @review.rate %>,
                  half: true,
                });
              </script>
            <div class="content">
              <p class="mt-3"><%=safe_join(@review.body.split("\n"),tag(:br))%></p>
            </div>
          </div>
          <div class="col-lg-4 text-right">
            投稿日：<%= @review.created_at.strftime('%Y年%m月%d日')%><br>
            <%= link_to "削除", admin_review_path(@review), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger mb-1" %>
            <div class="report-btn">
              <%= render 'admin/reviews/report-btn', review: @review %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="comment_box row">
      <div class="col-md-4 comment_field py-2"></div>
      <!--コメントを表示-->
      <div class="col-md-7 col-11 review_comments m-auto">
        <%= render 'public/comments/index', review: @review %>
      </div>
    </div>
  </div>
</div>