config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  namespace :admin do
    get 'homes/top'
  end

  #ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  #ユーザー新規登録、ログイン用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #管理者ログイン用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  scope module: :public do
    resources :users, only: [:show, :edit, :update, :destroy] do
      member do
        get :bookmarks
        get :visited_marks
        get :reviews
      end
    end
    resources :hot_springs, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
      resource :visited_marks, only: [:create, :destroy]
      resources :reviews, only: [:index, :show, :create, :edit, :update, :destroy] do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
        patch 'reports' => 'reviews#report', as: 'report'
      end
    end
    resources :contacts, only: [:new, :create]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :reviews
        get :comments
      end
    end
    resources :reviews, only:[:show, :destroy] do
      resources :comments, only: [:destroy]
      patch 'reports' => 'reviews#report', as: 'report'
    end
    resources :comments, only: [:index]
    resources :hot_springs, only: [:index, :show, :new, :create, :edit, :update]
    resources :contacts, only: [:index, :update]
  end

  # 画像が表示されなくなるため、削除
  # get '*path', controller: 'application', action: 'render_404'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/hot_spring.rb
class HotSpring < ApplicationRecord
  enum running_status: {running: 0, interrupt: 1, closed: 2 }

  has_many :reviews, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :visited_marks, dependent: :destroy
  has_many :hot_spring_qualities, dependent: :destroy
  has_many :qualities, through: :hot_spring_qualities
  has_many :hot_spring_tags, dependent: :destroy
  has_many :tags, through: :hot_spring_tags


  has_one_attached :hot_spring_image

  def get_hot_spring_image
    (hot_spring_image.attached?) ? hot_spring_image : 'noimage.png'
  end

  validates :name, presence: true, length: {minimum: 2, maximum: 30 }, uniqueness: true
  validates :introduction, presence: true, length: {maximum: 250}
  validates :address, presence: true, length: {maximum: 100}
  validates :price, presence: true, length: {maximum: 100}
  validates :private_bath_price, presence: true, length: {maximum: 100}
  validates :hours, presence: true, length: {maximum: 100}
  validates :holiday, presence: true, length: {maximum: 100}
  validates :parking, presence: true, length: {maximum: 100}
  validates :contact, presence: true, length: {maximum: 100}
  validates :running_status, presence: true
  validates :is_pablished, inclusion: { in: [true, false] }
  validates :hot_spring_qualities, presence: true
  
  geocoded_by :address
  after_validation :geocode
  
  scope :latest, -> {order(created_at: :desc)}
  scope :oldest, -> {order(created_at: :asc)}
  scope :rate_avg, -> {eager_load(:reviews).group("hot_springs.id").order("avg(reviews.rate) desc")}
  scope :review_amount, -> {eager_load(:reviews).group("hot_springs.id").order("count(reviews.hot_spring_id) desc")}
  
  def bookmarked_by?(user)
    bookmarks.exists?(user_id: user.id)
  end

  def visited_by?(user)
    visited_marks.exists?(user_id: user.id)
  end
  
  def self.looks(search)
    HotSpring.where("name LIKE?","%#{search}%")
  end

end

app/controllers/admin/hot_springs_controller.rb
class Admin::HotSpringsController < ApplicationController
  protect_from_forgery

  def index
    @hot_springs = HotSpring.page(params[:page])
  end

  def show
    @hot_spring = HotSpring.find(params[:id])
    quality_ids = @hot_spring.qualities.pluck(:id)
    effects = QualityEffect.where(quality_id: quality_ids).pluck(:effect_id).uniq
    @effects = Effect.where(id: effects)
  end

  def new
    @hot_spring = HotSpring.new
    #タグの追加を行えるようにしたい
    @tag = Tag.new
  end

  def create
    @hot_spring = HotSpring.new(hot_spring_params)
    if @hot_spring.save
      redirect_to admin_hot_spring_path(@hot_spring), notice: "温泉の新規登録に成功しました"
    else
      render 'new'
    end
  end

  def edit
    @hot_spring = HotSpring.find(params[:id])
    #タグの追加を行えるようにしたい
    @tag = Tag.new
  end

  def update
    @hot_spring = HotSpring.find(params[:id])
    if @hot_spring.update(hot_spring_params)
      redirect_to admin_hot_spring_path(@hot_spring), notice: "温泉情報の編集に成功しました"
    else
      render 'edit'
    end
  end

  private

  def hot_spring_params
    params.require(:hot_spring).permit(:name, :introduction, :price, :private_bath_price, :hours, :holiday, :address, :latitude, :longitude, :parking, :contact, :running_status, :is_pablished, :hot_spring_image, quality_ids: [], tag_ids: [] )
  end

end

app/helpers/admin/hot_springs_helper.rb
module Admin::HotSpringsHelper
end

app/views/admin/hot_springs/_form.html.erb
<%= form_with model: hot_spring, url: url, local: true do |f| %>
  <div class="table-responsive">
    <table class="table table-borderless">
      <tr class="field">
        <th class="align-middle"><%= f.label :hot_spring_image, "温泉画像", class: "m-0" %></th>
        <td><%= f.file_field :hot_spring_image, accept: "image/*" %></td>
      </tr>
      <tr class="field">
        <th class="align-middle"><%= f.label :name, "温泉名", class: "m-0" %></th>
        <td><%= f.text_field :name, autofocus: true, class: 'form-control' %></td>
      </tr>
      <tr class="field">
        <th><%= f.label :introduction, "紹介文", class: "m-0" %></th>
        <td><%= f.text_area :introduction, class: "form-control", rows: 5 %></td>
      </tr>
      <tr class="field">
        <th><%= f.label :quality_id, "泉質" %></th>
        <td class="check_box">
          <%= f.collection_check_boxes(:quality_ids, Quality.all, :id, :name) do |quality| %>
            <%= quality.label do %>
              <%= quality.check_box %>
              <%= quality.text %>
            <% end %>
          <% end %>
        </td>
      </tr>
      <tr class="field">
        <th class="align-middle"><%= f.label :address, "住所", class: "m-0" %></th>
        <td><%= f.text_field :address, placeholder: "住所　温泉名（地図表示のため）", class: "form-control" %></td>
      </tr>
      <tr class="field">
        <th class="align-middle"><%= f.label :price, "料金", class: "m-0" %></th>
        <td><%= f.text_field :price, class: "form-control" %></td>
      </tr>
      <tr class="field">
        <th class="align-middle"><%= f.label :private_bath_price, "貸切風呂料金", class: "m-0" %></th>
        <td><%= f.text_field :private_bath_price, class: "form-control" %></td>
      </tr>
      <tr class="field">
        <th class="align-middle"><%= f.label :hours, "立寄湯利用時間", class: "m-0" %></th>
        <td><%= f.text_field :hours, class: "form-control" %></td>
      </tr>
      <tr class="field">
        <th class="align-middle"><%= f.label :holiday, "定休日", class: "m-0" %></th>
        <td><%= f.text_field :holiday, class: "form-control" %></td>
      </tr>
      <tr class="field">
        <th class="align-middle"><%= f.label :parking, "駐車場", class: "m-0" %></th>
        <td><%= f.text_field :parking, class: "form-control" %></td>
      </tr>
      <tr class="field">
        <th class="align-middle"><%= f.label :contact, "問い合わせ先", class: "m-0" %></th>
        <td><%= f.text_field :contact, class: "form-control" %></td>
      </tr>
      <tr class="field align-middle">
        <th><%= f.label :running_status, "営業ステータス", class: "m-0", class: "m-0" %></th>
        <td>
          <div class="w-25 d-inline-block">
            <%= f.radio_button :running_status, :running  %>
            <%= f.label :running_status, "営業" %>
          </div>
          <div class="w-25 d-inline-block">
            <%= f.radio_button :running_status, :interrupt %>
            <%= f.label :running_status, "休業中" %>
          </div>
          <div class="w-25 d-inline-block">
            <%= f.radio_button :running_status, :closed %>
            <%= f.label :running_status, "閉業" %>
          </div>
        </td>
      </tr>
      <tr class="form-group align-middle text-nowrap">
        <th><%= f.label :is_pablished, "公開ステータス", class: "m-0" %></th>
        <td>
          <div class="w-25 d-inline-block">
            <%= f.radio_button :is_pablished, :true %>
            <%= f.label :is_pablished, "公開", value: :true %>
          </div>
          <div class="w-25 d-inline-block">
            <%= f.radio_button :is_pablished, :false %>
            <%= f.label :is_pablished, "非公開", value: :false %>
          </div>
        </td>
      </tr>
      <tr class="field">
        <th><%= f.label :tag_id, "タグ" %></th>
        <td class="check_box">
          <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <%= tag.label do %>
              <%= tag.check_box %>
              <%= tag.text %>
            <% end %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
  <div class="actions m-4 text-center">
    <%= f.submit message, class: "btn btn-success" %>
  </div>
<% end %>

<!-- タグの追加が行えるようにしたい-->
<%#= form_with model: @tag, local: true do |f| %>
  <%#= f.label :name, "新規タグ追加", class: "m-0" %>
  <%#= f.text_field :name %>
  <%#= f.submit "追加"%>
<%# end %>

app/views/admin/hot_springs/edit.html.erb
<div class="mx-auto col-11 col-sm-10 col-lg-8">
  <div class="my-2">
    <h4 class="col-md-4 bg-dark text-light text-center text-nowrap">温泉情報編集</h4>
    <div class="text-danger">
      <%= render"layouts/errors", obj: @hot_spring %>
    </div>
  </div>
  <div class="py-3">
    <%= render "form", hot_spring: @hot_spring, url: admin_hot_spring_path, message: "変更を保存" %>
  </div>
</div>

app/views/admin/hot_springs/index.html.erb
<div class="container">
    <div class="row py-4">
      <h4 class="col-lg-3 col-sm-5 col-8 bg-dark text-light text-center">温泉一覧</h4>
      <div class="col-lg-8 col-sm-5 col-2"></div>
      <div class="col-lg-1 col-sm-2 col-1 text-center pt-1">
        <%= link_to new_admin_hot_spring_path, class: "align-middle text-dark" do %>
          <i class="fa-2x fa-solid fa-circle-plus"></i>
        <% end %>
      </div>
    </div>
    <div class="row">
      <table class="table table-secondary table-border pb-3">
        <thead>
          <tr>
            <th>温泉ID</th>
            <th>温泉名</th>
            <th>営業ステータス</th>
            <th>公開ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @hot_springs.each do |hot_spring| %>
            <tr>
              <td><%= hot_spring.id %></td>
              <td>
                <%= link_to hot_spring.name, admin_hot_spring_path(hot_spring), class: "text-dark" %>
              </td>
              <td><%= hot_spring.running_status_i18n %></td>
              <td><%= hot_spring.is_pablished ? '公開' : '非公開'   %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @hot_springs %>
    </div>
</div>

app/views/admin/hot_springs/new.html.erb
<div class="mx-auto col-11 col-sm-10 col-lg-8">
  <div class="my-2">
    <h4 class="col-md-4 bg-dark text-light text-center text-nowrap">新規温泉登録</h4>
    <div class="text-danger">
      <%= render"layouts/errors", obj: @hot_spring %>
    </div>
  </div>
  <div class="py-3">
    <%= render "form", hot_spring: @hot_spring, url: admin_hot_springs_path, message: "登録" %>
  </div>
</div>

app/views/admin/hot_springs/show.html.erb
<div>
  <div class="row mx-auto my-2">
    <h4 class="col-lg-4 my-auto bg-dark text-light text-center"><%= @hot_spring.name %></h4>
    <div class="col-xl-8">
      <ul class="list-unstyled d-flex mt-3">
        <% @hot_spring.qualities.each do |quality| %>
          <li class="border border-danger text-danger rounded p-1"><%= quality.name %></li>　
        <% end %>
        <% @hot_spring.tags.each do |tag| %>
          <li class="border border-info text-info rounded p-1"><%= tag.name %></li>　
        <% end %>
      </ul>
    </div>
  </div>  
  <div class="row mx-auto">
    <div class="col-lg-4 col-md-6 text-center">
      <%= image_tag @hot_spring.get_hot_spring_image, size: "320x200", class: "w-100" %>
    </div>
    <div class="col-xl-8 col-lg-7 col-md-6 p-4 mx-auto">
      <%=safe_join(@hot_spring.introduction.split("\n"),tag(:br))%>
    </div>
  </div>
  
  <div class="p-4">
    <table class="table table-bordered table-dark">
      <tr>
        <th>住所</th>
        <td><%= @hot_spring.address %></td>
      </tr>
      <tr>
        <th>泉質</th>
        <td>
          <% @hot_spring.qualities.each do |quality| %>
            <%= quality.name %>　
          <% end %>
        </td>
      </tr>
      <tr>
        <th>泉質別適応症</th>
        <td>
          <% @effects.each do |effect| %>
            <%= effect.name %>　
          <% end %>
        </td>
      </tr>
      <tr>
        <th>料金</th>
        <td><%= @hot_spring.price %></td>
      </tr>
      <tr>
        <th>貸切風呂料金</th>
        <td><%= @hot_spring.private_bath_price %></td>
      </tr>
      <tr>
        <th>立寄利用時間</th>
        <td><%= @hot_spring.hours %></td>
      </tr>
      <tr>
        <th>定休日</th>
        <td><%= @hot_spring.holiday %></td>
      </tr>
      <tr>
        <th>駐車場</th>
        <td><%= @hot_spring.parking %></td>
      </tr>
      <tr>
        <th>問い合わせ先</th>
        <td><%= @hot_spring.contact %></td>
      </tr>
      <tr>
        <th>営業ステータス</th>
        <td><%= @hot_spring.running_status_i18n %></td>
      </tr>
      <tr>
        <th>公開ステータス</th>
        <td><%= @hot_spring.is_pablished ? "公開" : "非公開" %></td>
      </tr>
      
    </table>
    
    <!-- Googleマップ表示エリア(地図を表示) -->
    <div id="map"></div>
    
    <!-- Googleマップ表示用の Javascript -->
    <script>
      function initMap(){
        // 地図の位置情報(緯度・経度)を取得
        let mapPosition = {lat: <%= @hot_spring.latitude || 0 %> , lng: <%= @hot_spring.longitude || 0 %> };
        let map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: mapPosition
        });
        let transitLayer = new google.maps.TransitLayer();
        transitLayer.setMap(map);
    
        let contentString = '【住所】<%= @hot_spring.address %>';
        let infowindow = new google.maps.InfoWindow({
          content: contentString
        });
    
        let marker = new google.maps.Marker({
          position: mapPosition,
          map: map,
          title: contentString
        });
    
        marker.addListener('click', function(){
          infowindow.open(map, marker);
        });
      }
    </script>
    
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.google_map_api_key %>&callback=initMap" async defer></script>
    
    <div class="actions m-4 text-center">
      <%= link_to '編集する', edit_admin_hot_spring_path(@hot_spring), class: "btn btn-success" %>
    </div>
  </div>
</div>