config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  namespace :admin do
    get 'homes/top'
  end

  #ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  #ユーザー新規登録、ログイン用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #管理者ログイン用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  scope module: :public do
    resources :users, only: [:show, :edit, :update, :destroy] do
      member do
        get :bookmarks
        get :visited_marks
        get :reviews
      end
    end
    resources :hot_springs, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
      resource :visited_marks, only: [:create, :destroy]
      resources :reviews, only: [:index, :show, :create, :edit, :update, :destroy] do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
        patch 'reports' => 'reviews#report', as: 'report'
      end
    end
    resources :contacts, only: [:new, :create]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :reviews
        get :comments
      end
    end
    resources :reviews, only:[:show, :destroy] do
      resources :comments, only: [:destroy]
      patch 'reports' => 'reviews#report', as: 'report'
    end
    resources :comments, only: [:index]
    resources :hot_springs, only: [:index, :show, :new, :create, :edit, :update]
    resources :contacts, only: [:index, :update]
  end

  # 画像が表示されなくなるため、削除
  # get '*path', controller: 'application', action: 'render_404'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum sex: { unknown: 0, male: 1, female: 2 }

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :visited_marks, dependent: :destroy
  has_many :contacts, dependent: :destroy

  validates :sex, presence: true
  validates :birth_date, presence: true
  validates :username, presence: true, length: {minimum: 2, maximum: 20 }, uniqueness: true

  has_one_attached :profile_image

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'icon.png'
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
    user.password = SecureRandom.urlsafe_base64
    # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    user.username = "ゲスト"
    user.birth_date = Date.today
    user.sex = 0
    end
  end

  def age
    today = Time.zone.today
    this_years_birthday = Time.zone.local(today.year, birth_date.month, birth_date.day)
    age = today.year - birth_date.year
    if today < this_years_birthday
      age -= 1
    end
    "#{age} 歳"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "ユーザー情報を編集しました"
    else
      render 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_users_path, notice: "ユーザー情報を削除しました"
    else
      render 'show'
    end
  end
  
  def reviews
    @user = User.find(params[:id])
    reviews = Review.where(user_id: @user.id)
    @reviews = reviews.page(params[:page]).per(5).order(created_at: :DESC)
  end
  
  def comments
    @user = User.find(params[:id])
    comments = Comment.where(user_id: @user.id)
    @comments = comments.page(params[:page]).per(10).order(created_at: :DESC)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :sex, :birth_date, :email, :status, :profile_image)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/comments.html.erb
<div class="mx-auto">
  <h4 class="col-lg-5 col-md-6 bg-dark text-light text-center mb-3"><%= @user.username %> さんのコメント一覧</h4>
  <div class="pb-3">
    <div class="col-xl-10 mx-auto bg-light">
      <% @comments.each do |comment| %> 
        <div class="border-bottom p-2">
        
          <div class="row">
            <div class="col-md-8">
              <!--コメント表示-->
              <div class="content p-2">
                <p>
                  <%= link_to admin_review_path(comment.review_id), class: "text-dark" do %>
                    <%= safe_join(comment.comment.split("\n"),tag(:br)) %>
                  <% end %>
                </p>
              </div>
            </div>
            <div class="col-md-4 text-right">
              投稿日：<%= comment.created_at.strftime('%Y年%m月%d日')%><br>
            </div>
          </div>
        
        </div>
      <% end %>  
    </div>
    <%= paginate @comments, class: "text-center" %>
  </div>
</div>

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8">
      <div class="my-4">
        <h4 class="col-md-5 bg-dark text-light text-center">ユーザー情報編集</h4>
        <div class="text-danger">
          <%= render"layouts/errors", obj: @user %>
        </div>
      </div>
      <div class="table-responsive">
        <%= form_with model: @user, url:admin_user_path, method: :patch, local: true do |f| %>
          <table class="table table-borderless text-nowrap">
            <tr class="field">
              <th class="align-middle"><%= f.label :profile_image, "プロフィール画像", class: "m-0" %></th>
              <td><%= f.file_field :profile_image, accept: "image/*" %></td>
            </tr>
            <tr class="field">
              <th class="align-middle"><%= f.label :username, "ユーザーネーム", class: "m-0" %></th>
              <td><%= f.text_field :username, class: 'form-control' %></td>
            </tr>
            <tr class="field">
              <th><%= f.label :birth_date, "生年月日" %></th>
              <td><%= raw sprintf( f.date_select( :birth_date, use_month_numbers: true, start_year: 1930, end_year: (Time.now.year - 5), date_separator: '%s' ), '年 ', '月 ') + '日' %></td>
            </tr>
            <tr class="field align-middle">
              <th><%= f.label :sex, "性別" %></th>
              <td>
                <div class="w-25 d-inline-block">
                  <%= f.radio_button :sex, :male  %>
                  <%= f.label :sex, "男性"  %> 
                </div>
                <div class="d-inline-block">
                  <%= f.radio_button :sex, :female %>
                  <%= f.label :sex, "女性" %>
                </div>
              </td>
            </tr>
            <tr class="field">
              <th class="align-middle"><%= f.label :email, "メールアドレス", class: "m-0" %></th>
              <td><%= f.email_field :email, class: 'form-control' %></td>
            </tr>
          </table>
            <div class="actions m-4 text-center">
              <%= f.submit "編集を保存", class: "btn btn-success" %>
              
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="col-lg-3 col-sm-5 bg-dark text-light text-center my-2">ユーザー一覧</h4>
    <table class="table table-border table-secondary mt-4">
      <thead>
        <tr>
          <th>ユーザーID</th>
          <th>ユーザー名</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%=link_to user.username, admin_user_path(user),class: "text-dark" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/reviews.html.erb
<div class="mx-auto">
  <h4 class="col-lg-5 col-md-6 bg-dark text-light text-center mb-3"><%= @user.username %> さんのクチコミ一覧</h4>
  <div class="pb-3">
    <div class="col-xl-10 mx-auto bg-light">
      <!--レビューを１つずつ取り出して表示-->
      <% @reviews.each do |review| %>
        <div id="review_<%= review.id %>" class="row border-bottom p-2">
          <div class="col-lg-2 col-md-3 m-auto">
            <%= review.hot_spring.name %>
          </div>
          <!--レビュー内容-->
          <div class="col-lg-10 col-md-9">
            <div>
              <div class="row">
                <!--写真があれば表示-->
                <% if review.images.attached? %>
                  <!--画像を1つずつ取り出して表示-->
                  <% review.images.each do |image| %>
                    <div class="col-lg-4 col-md-6 mb-3">
                      <%= image_tag image, size: '320x200', class: "w-100" %>
                    </div>
                  <% end %>
                <% end %>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <!--レビュータイトル-->
                  <h5 class="title mt-2 border-bottom"><%= link_to review.title, admin_review_path(review), class: "text-dark" %></h5>
                  <!--星5段階評価表示-->
                  <div id="star-rate<%= review.id %>"></div>
                    <script>
                      raty(document.querySelector('#star-rate<%= review.id %>'),{
                        //星画像の指定などのオプションをここに
                        size      : 36,
                        starOff   : '<%= asset_path('star-off.png') %>',
                        starOn    : '<%= asset_path('star-on.png') %>',
                        starHalf: '<%= asset_path('star-half.png') %>',
                        readOnly: true,
                        score: <%= review.rate %>,
                        half: true,
                      });
                    </script>
                  <!--レビュー本文表示-->
                  <div class="content p-2">
                    <p><%=safe_join(review.body.split("\n"),tag(:br))%></p>
                  </div>
                </div>
                <div class="col-md-6 text-right">
                  投稿日：<%= review.created_at.strftime('%Y年%m月%d日')%><br>
                  <!--コメント数表示-->
                  <div class="comments-count d-inline">
                    コメント：<%= review.comments.count %>
                  </div>
                  
                  <!--非公開の場合の表示-->
                  <% if review.is_pablished == false %>
                    <p class="text-danger">（非公開の投稿です）</p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= paginate @reviews, class: "text-center" %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="mx-auto col-11 col-sm-10 col-lg-8">
  <div class="mt-4">
    <h4 class="col-lg-5 col-md-6 bg-dark text-light text-center">ユーザー登録情報</h4>
  </div>
  <div class="py-4">
    <table class="table table-border table-secondary">
      <tr>
        <th class="align-middle">プロフィール画像</th>
        <td><%= image_tag @user.get_profile_image, size: "70x70" %></td>
      </tr>
      <tr>
        <th class="align-middle">ユーザーネーム</th>
        <td><%= @user.username %></td>
      </tr>
      <tr>
        <th>生年月日</th>
        <td><%= @user.birth_date %></td>
      </tr>
      <tr class="field align-middle text-nowrap">
        <th>性別</th>
        <td><%= @user.sex %></td>
      </tr>
      <tr class="border-bottom">
        <th>メールアドレス</th>
        <td><%= @user.email %></td>
      </tr>
    </table>
    <% if @user.username != "ゲスト" %>
      <div class="actions my-4 text-center">
        <%= link_to '編集する', edit_admin_user_path(@user), class: "btn btn-success" %>
        <%= link_to '削除する', admin_user_path, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger" %>
      </div>
    <% end %>
  </div>
  <div class="m-2">
    <%= link_to reviews_admin_user_path(@user), class: "btn btn-primary" do %>
      投稿したクチコミ　（<%= @user.reviews.count %>）
    <% end %>
  </div>
  <div class="m-2">
    <%= link_to comments_admin_user_path(@user), class: "btn btn-primary" do %>
      投稿したコメント　（<%= @user.comments.count %>）
    <% end %>
  </div>
</div>