config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  namespace :admin do
    get 'homes/top'
  end

  #ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  #ユーザー新規登録、ログイン用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #管理者ログイン用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  scope module: :public do
    resources :users, only: [:show, :edit, :update, :destroy] do
      member do
        get :bookmarks
        get :visited_marks
        get :reviews
      end
    end
    resources :hot_springs, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
      resource :visited_marks, only: [:create, :destroy]
      resources :reviews, only: [:index, :show, :create, :edit, :update, :destroy] do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
        patch 'reports' => 'reviews#report', as: 'report'
      end
    end
    resources :contacts, only: [:new, :create]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :reviews
        get :comments
      end
    end
    resources :reviews, only:[:show, :destroy] do
      resources :comments, only: [:destroy]
      patch 'reports' => 'reviews#report', as: 'report'
    end
    resources :comments, only: [:index]
    resources :hot_springs, only: [:index, :show, :new, :create, :edit, :update]
    resources :contacts, only: [:index, :update]
  end

  # 画像が表示されなくなるため、削除
  # get '*path', controller: 'application', action: 'render_404'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="error_explanation text-danger">
    <h5><%= obj.errors.count %> 件のエラーが発生しました</h5>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-dark">
  <div class='container pt-3'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p class="text-light">- BeppuOnsen Note -</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>BeppuOnsen Note</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          
          <% if !admin_signed_in? %>
            <li>
              <%=  link_to about_path, class: 'nav-link text-light' do %>
                <i class="fa-regular fa-circle-question"></i> 別府温泉について
              <% end %>
            </li>
            <li>
              <%=  link_to hot_springs_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-list"></i> 温泉一覧
              <% end %>
            </li>
            
            <% if user_signed_in? %>
              <li class="small px-2 py-0 ">
                <div class="text-light">ユーザーネーム：<%= current_user.username %></div>
                <div class="d-flex">
                  <%= link_to user_path(current_user), class: 'nav-link text-light pr-2 p-0' do %>
                    <i class="fas fa-solid fa-user"></i> マイページ
                  <% end %>
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light p-0' do %>
                    <i class="fas fa-sign-out-alt"></i> ログアウト
                  <% end %>
                </div>
              </li>
              <li>
                <%= link_to new_contact_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-regular fa-envelope"></i>
                <% end %>
              </li>
              
            <% else %>
              <li>
                <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-user-plus"></i> 新規登録
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-in-alt"></i> ログイン
                <% end %>
              </li>
            <% end %>
            
          <% else %>
            <li><%= link_to "クチコミ一覧", admin_root_path, class: 'nav-link text-light'%></li>
            <li><%= link_to "コメント一覧", admin_comments_path, class: 'nav-link text-light'%></li>
            <li><%= link_to "温泉一覧", admin_hot_springs_path, class: 'nav-link text-light'%></li>
            <li><%= link_to "ユーザー一覧", admin_users_path, class: 'nav-link text-light'%></li>
            <li><%= link_to "問い合わせ一覧", admin_contacts_path, class: 'nav-link text-light'%></li>
            <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-light'%></li>
          <% end %>
          
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeppuOnsen Note</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/13f2c566e6.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main id="main" class="min-vh-100">
      <div class="container">
        <% if flash[:notice] %>
          <div class="alert alert-secondary text-success mb-0">
            <%= notice %><button type="button" class="close" data-dismiss="alert">&times;</button>
          </div>
        <% end %>
        <div class="text-danger">
          <p class="alert m-0">
            <%= alert %>
          </p>
        </div>
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>